<h1 align="center">Hands-On Machine Learning | AI2YOU</font></h1>
<br>
<p style="text-align: center;align:center"><font size = 5>Polynomial Regression</font></p>
<h3 align="center">Zahra Amini</h3>
<br>
<br>
<br>
<br>
<br>

In [1]:
import numpy as np

In [2]:
from sklearn.linear_model import LinearRegression

In [3]:
X = np.array([[0],[1],[2],[3],[4]])

y=np.array([[12],[19],[29],[37],[45]])

In [5]:
LR = LinearRegression()

In [6]:
LR.fit(X, y)

LinearRegression()

In [7]:
LR.coef_

array([[8.4]])

In [8]:
LR.intercept_

array([11.6])

In [9]:
from sklearn.preprocessing import PolynomialFeatures

In [10]:
X = np.array([[2, 3]])

In [14]:
poly_conv = PolynomialFeatures(degree=3, include_bias=False)#, include_bias=True)

In [15]:
X_poly = poly_conv.fit_transform(X)

In [13]:
X_poly # TRUE

array([[ 1.,  2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])

In [16]:
X_poly # FALSE

array([[ 2.,  3.,  4.,  6.,  9.,  8., 12., 18., 27.]])