<img src="AI2YOU.png">

<h1 align="center"><font size = 14>Machine Learning</font></h1>
<h4 align="center">February, 2023<h4>
<h3 align="center"><font size = 7>Numpy</font></h3>
<h1 align="center">Part2</h1>
<h4 align="center">P01V03</h4>
<br>
<h1 align="center"><font size = 6>AI2YOU | Zahra Amini</font></h1>
<br>
<br>
<br>
<br>
<br>

# Import NumPy Library

In [1]:
import numpy as np

# 4. random choice

random.choice(a, size=None, replace=True, p=None)

In [2]:
np.random.choice([1, 3, 5, 7, 9])

3

In [3]:
np.random.choice([1, 3, 5, 7, 9], size=3)

array([7, 7, 5])

In [4]:
np.random.choice(5, size=5)

array([0, 0, 4, 0, 1])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
np.random.choice(5, size=5, replace=False)

array([3, 4, 2, 1, 0])

In [7]:
np.random.choice(5, size=5, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 3, 2, 3, 2])

In [8]:
np.random.choice(5, size=3,replace=False, p=[0.1, 0, 0.3, 0.6, 0])

array([3, 2, 0])

In [9]:
np.random.choice([3, 5, 8, 12], size=(3, 5))

array([[ 5, 12,  3,  8,  5],
       [ 3, 12, 12,  5,  5],
       [ 5,  3,  5,  3,  3]])

In [10]:
animal = ['pooh', 'rabbit', 'bird', 'Pirooz']

np.random.choice(animal, size=3, replace=False, p=[0.3, 0, 0.1, 0.6])

array(['pooh', 'bird', 'Pirooz'], dtype='<U6')

# 5. Adding, removing, and sorting elements

## Adding

In [11]:
np.append([1, 2, 3], [[4, 5, 6], [7, 8, 9]])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.append([[1, 2, 3], [4, 5, 6]], [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
np.append([[1, 2], [3, 4]], [[5, 6], [7, 8]], axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

## Removing

In [14]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
np.delete(arr, 0, axis=0)

array([[4, 5, 6],
       [7, 8, 9]])

In [16]:
np.delete(arr, 0, axis=1)

array([[2, 3],
       [5, 6],
       [8, 9]])

In [17]:
np.delete(arr, 0)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
np.delete(arr, [0, 1], axis=0)

array([[7, 8, 9]])

In [19]:
np.delete(arr, [0, 2], axis=1)

array([[2],
       [5],
       [8]])

## Sorting

In [20]:
arr2 = np.array([2, 7, 3, 4, 6, 1, -5])
arr2

array([ 2,  7,  3,  4,  6,  1, -5])

In [21]:
np.sort(arr2) # ascending

array([-5,  1,  2,  3,  4,  6,  7])

In [22]:
arr3 = np.array([[2, 1, 5], [0, 7, 3], [8, 6, 9]])

arr3

array([[2, 1, 5],
       [0, 7, 3],
       [8, 6, 9]])

In [23]:
np.sort(arr3, axis=None)

array([0, 1, 2, 3, 5, 6, 7, 8, 9])

In [24]:
np.sort(arr3, axis=0)

array([[0, 1, 3],
       [2, 6, 5],
       [8, 7, 9]])

In [25]:
np.sort(arr3, axis=1)

array([[1, 2, 5],
       [0, 3, 7],
       [6, 8, 9]])

In [26]:
np.flip(np.sort(arr2))

array([ 7,  6,  4,  3,  2,  1, -5])

## concatenate

In [27]:
a = np.array([1, 2, 3, 4])

b= np.array([5, 6, 7, 8])

In [28]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [29]:
np.concatenate((b, a))

array([5, 6, 7, 8, 1, 2, 3, 4])

In [30]:
c = np.array([[1, 2], [3, 4]])

d = np.array([[5, 6]])

In [31]:
np.concatenate((c, d), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [32]:
np.concatenate((c, d.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [33]:
np.concatenate((c, d), axis=None)

array([1, 2, 3, 4, 5, 6])

## ndarray.ndim, ndarray.size, ndarray.shape

In [34]:
arr4 = np.array([[[0, 1],
                 [2, 3]],
                
                [[4, 5],
                [6, 7]],
                
                [[8, 9],
                [10, 11]]])

arr4

array([[[ 0,  1],
        [ 2,  3]],

       [[ 4,  5],
        [ 6,  7]],

       [[ 8,  9],
        [10, 11]]])

In [35]:
arr4.ndim

3

In [36]:
arr4.size

12

In [37]:
arr4.shape

(3, 2, 2)

# 6. Reshape an array

In [38]:
arr5 = np.arange(6)

arr5

array([0, 1, 2, 3, 4, 5])

In [39]:
arr5.reshape(3, 2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [40]:
arr5.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

# 7. sum, max, min, mean

In [41]:
arr3

array([[2, 1, 5],
       [0, 7, 3],
       [8, 6, 9]])

In [42]:
arr3.sum()

41

In [43]:
arr3.sum(0)

array([10, 14, 17])

In [44]:
arr3.sum(1)

array([ 8, 10, 23])

In [45]:
arr3.max()

9

In [46]:
arr3.max(0)

array([8, 7, 9])

In [47]:
arr3.max(1)

array([5, 7, 9])

In [48]:
arr3.min()

0

In [49]:
arr3.mean()

4.555555555555555

In [50]:
(arr3.sum())/(arr3.size)

4.555555555555555

## unique()

In [51]:
arr6 = np.array([[1, 2, 5, 7], [1, 5, 4, 3], [2, 4, 6, 6]])

arr6

array([[1, 2, 5, 7],
       [1, 5, 4, 3],
       [2, 4, 6, 6]])

In [52]:
np.unique(arr6)

array([1, 2, 3, 4, 5, 6, 7])

# 8. Boolean Indexing

In [53]:
arr7 = np.array([[1, 2], [3, 4], [5, 6]])

arr7

array([[1, 2],
       [3, 4],
       [5, 6]])

In [54]:
arr7 > 2

array([[False, False],
       [ True,  True],
       [ True,  True]])

In [55]:
arr7 > 5

array([[False, False],
       [False, False],
       [False,  True]])

In [56]:
arr7[arr7 > 5]

array([6])

In [57]:
arr7[arr7 > 2]

array([3, 4, 5, 6])

In [58]:
arr7[(arr7>2) & (arr7<5)]

array([3, 4])

In [59]:
arr7[(arr7>2) | (arr7<5)]

array([1, 2, 3, 4, 5, 6])

In [60]:
arr7[arr7 % 2 == 0]

array([2, 4, 6])

In [61]:
arr7[arr7 % 2 != 0]

array([1, 3, 5])

In [62]:
int(True)

1

In [63]:
int(False)

0

# 9. Slicing

In [64]:
arr8 = np.array([0, 1, 2, 3, 4, 5, 6])

arr8

array([0, 1, 2, 3, 4, 5, 6])

In [65]:
arr8[2]

2

In [66]:
arr8[5]

5

In [67]:
arr8[:]

array([0, 1, 2, 3, 4, 5, 6])

In [68]:
arr8[2:]

array([2, 3, 4, 5, 6])

In [69]:
arr8[:4]

array([0, 1, 2, 3])

In [70]:
arr8[2:4]

array([2, 3])

In [71]:
arr9 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])

arr9

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [72]:
arr9[2]

array([6, 7, 8])

In [73]:
arr9[:, 2]

array([ 2,  5,  8, 11])

In [74]:
arr9[:2, 1:3]

array([[1, 2],
       [4, 5]])

# Finished!