<img src="AI2YOU.png">

<h1 align="center"><font size = 14>Machine Learning</font></h1>
<h4 align="center">February, 2023<h4>
<h3 align="center"><font size = 7>Numpy</font></h3>
<h1 align="center">Part1</h1>
<h4 align="center">P01V02</h4>
<br>
<h1 align="center"><font size = 6><a href = "https://www.youtube.com/@AI2YOU">AI2YOU</a> | Zahra Amini</font></h1>
<br>
<br>
<br>
<br>
<br>

# 1. Import NumPy Library

In [1]:
import numpy as np

# 2. Array

numpy.array(object, dtype=None, *, copy=True, order='K', subok=False, ndmin=0, like=None)

In [2]:
np.array([1, 2, 3, 4, 5])

array([1, 2, 3, 4, 5])

In [3]:
type(np.array((1, 2, 3, 4, 5)))

numpy.ndarray

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [5]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
a.shape

(2, 3)

In [7]:
a.dtype

dtype('int32')

In [8]:
b = np.array([[1.1, 2.5, 3.4], [2.2, 4.7, 8.1], [0, 0, 0]])

In [9]:
b.dtype

dtype('float64')

In [10]:
b

array([[1.1, 2.5, 3.4],
       [2.2, 4.7, 8.1],
       [0. , 0. , 0. ]])

In [11]:
np.array([1, 2, 3], dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [12]:
np.array([1, 2j, 3], dtype=complex)

array([1.+0.j, 0.+2.j, 3.+0.j])

# 2. Zeros, Ones and Empty Arrays

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.ones(3)

array([1., 1., 1.])

In [16]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
# Create an empty array with 3 elements

np.empty(3)

array([1., 1., 1.])

In [18]:
np.empty((2, 4))

array([[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [0.00000000e+000, 8.10267659e-321, 1.57450889e-234,
        8.17531756e-201]])

# 3. Random Numbers

## 3.1 randint

random.randint(low, high=None, size=None, dtype=int)

In [19]:
#Generate a random integer from 0 to 100

np.random.randint(100)

55

In [20]:
# Generate 5 random integers from 0 to 100

np.random.randint(100, size = (5))

array([38, 67, 16,  6, 71])

In [21]:
# Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100

np.random.randint(100, size = (3, 5))

array([[ 1, 21, 68, 65, 35],
       [71, 83,  3, 47, 89],
       [91, 67, 63, 41, 39]])

In [22]:
np.random.randint(10, 100, size = (5))

array([97, 99, 10, 70, 30])

In [23]:
# Generate a 1 x 3 array with 3 different upper bounds

np.random.randint(1, [3, 5, 10])

array([1, 3, 5])

In [24]:
# Generate a 1 by 3 array with 3 different lower bounds

np.random.randint([1, 5, 7], 10)

array([3, 5, 8])

In [25]:
np.random.randint([1, 2, 3], [5, 7, 8])

array([1, 4, 4])

In [26]:
# Generate a 2 by 4 array using broadcasting with dtype of uint8

np.random.randint([1, 3, 5, 7], [[10], [40]], dtype = np.uint8)

array([[ 6,  3,  6,  8],
       [ 2, 37, 30, 21]], dtype=uint8)

## 3.2 rand

random.rand(d0, d1, ..., dn)

In [27]:
# Generate a random float from 0 to 1

np.random.rand()

0.48827835896753713

In [28]:
# Generate a 1-D array containing 5 random floats

np.random.rand(5)

array([0.43941887, 0.73581111, 0.3747201 , 0.81009473, 0.07362101])

In [29]:
# Generate a 2-D array with 3 rows, each row containing 5 random numbers

np.random.rand(3, 5)

array([[0.8898871 , 0.72761294, 0.43451335, 0.82079432, 0.54048863],
       [0.71933977, 0.32869493, 0.96625334, 0.14450537, 0.5143952 ],
       [0.94008947, 0.89169806, 0.98972739, 0.24914937, 0.95232016]])

## 3.3 arange

numpy.arange([start, ]stop, [step, ]dtype=None, *, like=None)

In [30]:
np.arange(3)

array([0, 1, 2])

In [31]:
np.arange(3.5)

array([0., 1., 2., 3.])

In [32]:
np.arange(3, 7)

array([3, 4, 5, 6])

In [33]:
np.arange(1, 12, 2)

array([ 1,  3,  5,  7,  9, 11])

In [34]:
# Let's create an array of every even number from ten (inclusive) to fifty (exclusive)

np.arange(10 ,50, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

In [35]:
np.arange(0, 5, 0.5, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [36]:
np.arange(0, 5, 0.5, dtype = float)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [37]:
np.arange(-3, 3, 0.5, dtype=float)

array([-3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,  1. ,  1.5,  2. ,
        2.5])

#### The built-in range generates Python built-in integers that have arbitrary size, while numpy.arange produces numpy.int32 or numpy.int64 numbers. This may result in incorrect results for large integer values:

In [38]:
# range  arange

list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [39]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [40]:
power = 40

x1 = [(n ** power) % 10000 for n in range(8)]

x2 = [(n ** power) % 10000 for n in np.arange(8)]


print(x1)

print(x2)

[0, 1, 7776, 8801, 6176, 625, 6576, 4001]
[0, 1, 0, 6897, 0, 3617, 0, 1537]


## 3.4 linspace

numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [41]:
# 15 numbers from 0 (inclusive) to 2 (inclusive)

d = np.linspace(0, 2, num=15)

In [42]:
d

array([0.        , 0.14285714, 0.28571429, 0.42857143, 0.57142857,
       0.71428571, 0.85714286, 1.        , 1.14285714, 1.28571429,
       1.42857143, 1.57142857, 1.71428571, 1.85714286, 2.        ])

In [43]:
d[2] - d[1]

0.14285714285714285

In [44]:
d[3] - d[2]

0.14285714285714285

In [45]:
np.linspace(2, 3, 5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [46]:
np.linspace(2, 3, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [47]:
f = np.linspace(2, 3, num=5, endpoint=False, retstep=True)

In [48]:
f

(array([2. , 2.2, 2.4, 2.6, 2.8]), 0.2)

In [49]:
f[0]

array([2. , 2.2, 2.4, 2.6, 2.8])

In [50]:
f[1]

0.2

# Finished!